/**
 * Curated inline glossary context.
 *
 * We intentionally do not annotate every word that happens to match a glossary
 * alias. A term is eligible only when it is semantically relevant to the
 * knowledge chapter. This prevents collisions such as Kubernetes "Pod" vs the
 * Polish preposition "pod", or framework terms used in an unrelated sense.
 */
const SECTION_TERMS: Record<string, string[]> = {
  // JavaScript
  "js-execution": ["js","runtime","compiler","interpreter","event-loop"],
  "js-bindings": ["scope","closure"],
  "js-types": ["json"],
  "js-functions": ["scope","closure"],
  "js-operators-basics": [],
  "js-conditions-basics": [],
  "js-loops-basics": [],
  "js-arrays-basics": [],
  "js-objects-basics": ["json","prototype"],
  "js-destructuring-spread": [],
  "js-closures": ["closure","scope"],
  "js-prototypes-this": ["prototype"],
  "js-event-loop": ["event-loop","microtask","promise"],
  "js-modules-errors": ["esm","npm","node"],
  "js-references": [],
  "js-iterators-generators": [],

  // TypeScript
  "ts-mental-model": ["ts","js","compiler","runtime","type-inference"],
  "ts-functions": ["ts","type-inference","generic"],
  "ts-objects-unions": ["union","narrowing"],
  "ts-generics": ["generic","type-inference"],
  "ts-primitives-literals": ["ts","union"],
  "ts-arrays-tuples": ["ts","generic"],
  "ts-null-undefined": ["unknown","never","narrowing"],
  "ts-alias-interface": ["structural-typing"],
  "ts-readonly": ["ts"],
  "ts-utility-basics": ["generic"],
  "ts-narrowing": ["narrowing","unknown","never"],
  "ts-type-transformations": ["generic","union"],
  "ts-boundaries": ["unknown","json","api"],
  "ts-compiler": ["tsconfig","strict","compiler"],
  "ts-conditional-infer": ["generic","type-inference"],
  "ts-template-literals": ["union"],

  // React
  "react-components": ["component","jsx","props"],
  "react-props-state": ["props","state","component"],
  "react-events-lists": ["component","state"],
  "react-effects": ["effect","state"],
  "react-mental-model": ["component","state","props","reconciliation"],
  "react-jsx-basics": ["jsx","component","props"],
  "react-conditional-ui": ["jsx","state"],
  "react-forms-basics": ["state","ref"],
  "react-lifting-state": ["state","props"],
  "react-refs-basics": ["ref","dom"],
  "react-render-model": ["reconciliation","state","props"],
  "react-state-architecture": ["state","context"],
  "react-performance": ["memoization","reconciliation"],
  "react-async-testing-a11y": ["effect","api"],
  "react-reconciliation": ["reconciliation","jsx"],
  "react-transitions": ["state"],

  // AI
  "ai-landscape": ["ai","ml","llm","model","inference"],
  "ai-tokens-context": ["token","context-window","llm"],
  "ai-prompting": ["prompt","llm","context-window"],
  "ai-structured-output": ["json","llm"],
  "ai-embeddings": ["embedding","vector-db"],
  "ai-rag": ["rag","embedding","vector-db","llm"],
  "ai-retrieval-design": ["embedding","reranking","vector-db","rag"],
  "ai-tools": ["tool-calling","api","agent"],
  "ai-mcp": ["mcp","tool-calling","agent"],
  "ai-evals": ["eval","model","llm"],
  "ai-security": ["prompt-injection","agent","tool-calling"],
  "ai-hybrid-reranking": ["reranking","embedding","vector-db","rag"],
  "ai-agents": ["agent","tool-calling","mcp","eval"],
  "ai-memory": ["context-window","embedding","vector-db"],
  "ai-finetuning": ["fine-tuning","rag","model"],
  "ai-routing": ["model","inference","eval"],
  "ai-performance": ["inference","token","cache"],
  "ai-observability": ["eval","agent","tool-calling"],
  "ai-production": ["rag","mcp","eval","agent","model"],

  // IT / production foundations
  "it-request-journey": ["url","dns","tls","http","cdn"],
  "it-browser-rendering": ["dom","reflow","repaint","js"],
  "it-dns": ["dns","ipv4","ipv6","cdn"],
  "it-network-tls": ["tcp","quic","udp","tls","https"],
  "it-http": ["http","headers","status-code","https"],
  "it-cors": ["cors","preflight","origin","same-origin","http"],
  "it-caching": ["cache","cdn","headers"],
  "it-browser-state": ["cookie","localstorage","sessionstorage","indexeddb","session"],
  "it-frontend-backend": ["api","bff","js"],
  "it-apis": ["api","rest","graphql","rpc","endpoint"],
  "it-auth": ["session","jwt","access-token","refresh-token"],
  "it-oauth-oidc-sso": ["oauth","oidc","sso","pkce","access-token"],
  "it-databases": ["sql","acid","transaction","db-index","primary-key","foreign-key"],
  "it-nosql": ["nosql","sharding","replication"],
  "it-redis-cache": ["redis","cache"],
  "it-queues": ["message-queue","pub-sub","event-driven"],
  "it-storage-cdn": ["cdn","cache","aws","azure"],
  "it-runtime-units": ["process","vm","container","runtime","os"],
  "it-proxy-loadbalancer": ["reverse-proxy","load-balancer","nginx","tls"],
  "it-cloud": ["aws","azure","gcp","serverless","vm"],
  "it-aws-azure": ["aws","azure","gcp","iam","vpc"],
  "it-docker": ["docker","container","artifact"],
  "it-kubernetes": ["kubernetes","pod","container","autoscaling","load-balancer"],
  "it-terraform": ["terraform","iac","environment"],
  "it-cicd": ["cicd","pipeline","artifact","deployment","rollback"],
  "it-config-secrets": ["environment","secret","kms","iam"],
  "it-observability": ["sli","slo"],
  "it-web-security": ["xss","csrf","csp","tls","hashing","encryption"],
  "it-scaling": ["autoscaling","load-balancer","scalability","stateless"],
  "it-networking-cloud": ["vpc","subnet","nat","gateway","firewall","vpn"],
  "it-consistency-idempotency": ["transaction","event-driven","message-queue"],
  "it-resilience": ["availability","load-balancer"],
  "it-deployments": ["deployment","rollback","blue-green","canary","artifact"],
  "it-k8s-production": ["kubernetes","pod","autoscaling","sli","slo"],
  "it-secrets-kms": ["secret","kms","iam","encryption"],
  "it-slo": ["sli","slo","availability"],
  "it-incidents": ["sli","slo","rollback"],
  "it-disaster-recovery": ["rto","rpo","replication","availability"],
  "it-architecture": ["monolith","microservices","bff","event-driven","stateless","stateful"],
  "it-production-journey": [
    "dns","cdn","load-balancer","bff","api","cache","sql","message-queue",
    "cicd","terraform","kubernetes",
  ],
};

export function glossaryTermsForSection(sectionId: string): string[] {
  return SECTION_TERMS[sectionId] ?? [];
}
